#!/usr/bin/env python3
"""ttx - teletext page composer with sixel output."""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from teletext.cli import main

if __name__ == '__main__':
    sys.exit(main())
